#!/bin/bash

# Set environment variables
export AGGREGATION_NODE_RPC_URL=http://localhost:4500/relayer-server

export DATABASE_URL=mongodb://localhost:27017/
export DATABASE_NAME=RN1
# Start the application
npm run dev
